### ISSUE TITLE
Add the option to permit links and text customisation in the notes section

### ISSUE THREAD

**Issue by Geroimparable** [alicolville/meal-tracker#140]
Before the notes section on the admin panel, allowed links via html code, but now is not working. Would be nice to allow us to put links on the notes, or list, format, Thank you

**Comment by alicolville** [comment]
Is this for Meal Tracker or Weight Tracker?

Could you send a screen shot of what you're looking at please/

**Comment by alicolville** [comment]
Ah, could you raise here please:

https://github.com/alicolville/Weight-Tracker/issues
