### ISSUE TITLE
Simple Add Meal Button

### ISSUE THREAD

**Issue by YOPT21** [alicolville/meal-tracker#143]
The only way to add a meal is via the main shortcode that shows everything. Can a simple button be added that a user can click and then allows them to input their meal? (Picture ref.. so they click the button and then a bit pops up that allows user to pick which meal time and then add the meal)
![Screenshot_20220626-092845_Chrome](https://user-images.githubusercontent.com/82499071/175806224-cdd0d0fe-c780-40e9-ad4d-2b5dd77e6c43.jpg)

**Comment by YOPT21** [comment]
Or is there a shortcode that allows me to hide the pie chart?

**Comment by alicolville** [comment]
Yes, both could both be done. I could look at an argument for the existing shortcode to hide the chart.

**Comment by YOPT21** [comment]
That would be perfect. Thanks.

**Comment by alicolville** [comment]
This will be in the next release 3.0.11
