### ISSUE TITLE
Copy Food Entries from User to Admin

### ISSUE THREAD

**Issue by sbservices** [alicolville/meal-tracker#149]
In a bid to populate the food database with 1000's of items, a number of the coaches went and added approx 1000 items each using their own account.  We had 'Other user's food items' = Yes, so that every member could see all those entries to get everyone started quickly.  However, we now would like to turn this off and transfer food items added by a number of the coaches over to the admin area so that they are accessible by members.

I can see there is an import feature, but I cannot find anything to export the items.  If I could export each of the coaches food lists, I could import them in to the admin area and then turn off 'Other users's food items'. Is this possible please?  Thanks

**Comment by alicolville** [comment]
I'm afraid there isn't an export function at the moment.

The easiest way would be to look at the meals table in your database and set the flag to false for the relevant user IDs (or SQL export/import)

**Comment by sbservices** [comment]
Thanks. So if I set the flag to false, does this make them an admin item?

**Comment by sbservices** [comment]
For anyone else wanting to do this, I used

UPDATE wp_yk_mt_meals SET 
added_by_admin = "1" WHERE
added_by = "2" 

This is where the User ID was 2, which copied all the entries this user had added over to the 'admin' area in Meal Tracker.
Cheers Ali
