### ISSUE TITLE
Importing CSV loses the decimal

### ISSUE THREAD

**Issue by sbservices** [alicolville/meal-tracker#162]
When using the CSV import method, we seem to be losing a decimal on the values.

<img width="1251" alt="image" src="https://github.com/alicolville/meal-tracker/assets/101115016/f7c44789-f1d4-4c1a-9402-d35805569fc4">

**Comment by sbservices** [comment]
reminder

**Comment by alicolville** [comment]
Fixed - will be in 3.1
