### ISSUE TITLE
Future of Meal Tracker

### ISSUE THREAD

**Issue by YOPT21** [alicolville/meal-tracker#163]
Hey Ali, I just wondered if there was a road map of what is expected on the meal tracker? Like are you integrating it into the weight tracker dashboard, barcode scanning, more end user editing etc?? Would just like to know if we should be expecting more from this plugin or if its what it is now.

Cheers

**Comment by alicolville** [comment]
Hi mate,

Mira a fair question, I’ve not released too much on Meal Tracker recently as I’ve been swamped and moved house etc!

I’m hoping to get more features out this year, but don’t have a road map per se I’m afraid.

I’ve a release waiting to go out, but that is more of a maintenance release I’m afraid.

Al

**Comment by YOPT21** [comment]
The fun and joys of moving house. Hope it's all going well. I'll keep my eyes peeled over the rest of the year for future updates. Just got to get my clients away from Nutracheck lol
