### ISSUE TITLE
Add a message to say if using Weight Tracker to complete their profile

### ISSUE THREAD

**Issue by sbservices** [alicolville/meal-tracker#174]
When a user goes to track their food, but they haven't filled in their Weight Tracker food settings and they land here, when they click 'save settings' it doesn't tell them that they need to have filled in their **Preferences** in the Weight Tracking area first for them to be able to use the Food Tracker because their calories cannot be calculated until they've filled them in.

So it just sits here at this screen

<img width="752" alt="image" src="https://github.com/alicolville/meal-tracker/assets/101115016/f7d18a99-fdd9-4cde-90a1-3529f8008bab">

**Comment by alicolville** [comment]
Ah that's a good idea. I'll add that

**Comment by sbservices** [comment]
cheers!! I thought if it took me a while to figure it out, someone new and less techy as an end user might be inclined to think its not working and bin it off. LOL
Perhaps make it a clickable link to the 'users preference settings' or something. Thanks a mill.

**Comment by alicolville** [comment]
Thinking this: 
<img width="1177" alt="image" src="https://github.com/alicolville/meal-tracker/assets/10127199/8a2e3dd2-982b-4ec1-8bce-13df3b34c603">

**Comment by alicolville** [comment]
Will be in 3.1.5.
