### ISSUE TITLE
Frontend Shortcodes

### ISSUE THREAD

**Issue by mybestrong** [alicolville/meal-tracker#57]
Add front end shortcodes with the following functionality;

* **Chart / Graph**
  * Pie Chart
  * Line Chart of all entries
  * Entries

* **Text Shortcodes**
  * Latest Entry date
  * First entry date
  * Number entries
  * Number meals

* **Meals**
  * List all meals by user
  * List all meals by all users
  * List meals by meal type (breakfast, morning, lunch etc etc)

**Comment by yekenuk** [comment]
There is always one that wants more! :)

**Comment by mybestrong** [comment]
You love me really xxxxxx

Rick Wilson
 
Be  Strong UK Ltd
 
www.mybestrong.com

**Comment by alicolville** [comment]
Partially completed in 3.0. Won't do the meal ones.
