### ISSUE TITLE
Add Macro Nutrients

### ISSUE THREAD

**Issue by paulrjohnson1404** [alicolville/meal-tracker#76]
It would be great to add

- Carbs

- Protein

- Fat

These are normally detailed in external databases and used by most people who tracking their daily consumption

**Comment by yekenuk** [comment]
On the list :)

**Comment by alicolville** [comment]
These are implemented in a basic form in version 2.0. Allows users to add and edit MacroN values in the front end. I intend to expand on this in further releases.

**Comment by alicolville** [comment]
Done :)
